name: robots_mars_challenge
description: An implementation of the Mars robots challenge.
version: 1.0.0
repository: https://github.com/lcsmil/robots-mars-challenge

environment:
  sdk: ^3.10.7

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
